//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Tasks
    {
        public int idTask { get; set; }
        public string NameTask { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idProject { get; set; }
        public Nullable<int> idStatus { get; set; }
        public Nullable<int> idTeam { get; set; }

        [JsonIgnore]
        public virtual Project Project { get; set; }
        [JsonIgnore]
        public virtual Status Status { get; set; }
        [JsonIgnore]
        public virtual Teams Teams { get; set; }
        [JsonIgnore]
        public virtual Users Users { get; set; }
    }
}
